// ── CITY DATA ─────────────────────────────────────────────────────────────────
// All buildings, districts, project content, education content

window.CITY_DATA = {

  // Player start position
  playerStart: { x: 0, z: 8 },

  // ── DISTRICTS ────────────────────────────────────────────────────────────────
  districts: [
    {
      id: 'hero',
      name: 'HERO DISTRICT',
      color: 0x001a2e,
      center: [0, -6],
      radius: 14,
    },
    {
      id: 'education',
      name: 'EDUCATION QUARTER',
      color: 0x0a1a0a,
      center: [0, -32],
      radius: 12,
    },
    {
      id: 'cloud',
      name: 'CLOUD DISTRICT',
      color: 0x00111a,
      center: [28, 0],
      radius: 10,
    },
    {
      id: 'foundation',
      name: 'FOUNDATION ZONE',
      color: 0x120800,
      center: [-28, 0],
      radius: 10,
    },
  ],

  // ── BUILDINGS ────────────────────────────────────────────────────────────────
  buildings: [

    // ── HERO: Auth Tower ──────────────────────────────────────────────────────
    {
      id: 'auth-tower',
      name: 'Auth Tower',
      subtitle: 'SSO PLATFORM',
      district: 'hero',
      pos: [-8, -4],
      size: [5, 5],
      height: 16,
      color: 0x0044aa,
      glowColor: '#00c8ff',
      roofColor: 0x0066cc,
      windowColor: 0x88ddff,
      type: 'skyscraper',
      isHero: true,
      icon: '🏛️',
      tag: 'SSO · JWT · PASSKEY · RBAC',
      status: 'OPERATIONAL',
      year: '2024',
      metrics: [{ v: '10+', l: 'APPS' }, { v: '10K+', l: 'SESSIONS' }, { v: '0', l: 'BREACHES' }],
      story: 'Every internal application had its own login system. Employees juggled separate credentials for each tool. When someone left, IT had to manually revoke access from every system — a process that could take days.\n\n<em>Aditya built a centralized SSO platform from scratch.</em> One login works across every application. One logout disconnects from all. Offboarding takes a single action.',
      outcome: 'Zero breaches since deployment. 10+ apps unified under one identity layer.',
      tech: ['Java 17', 'Spring Boot', 'JWT RS256', 'MySQL 8', 'WebAuthn', 'RBAC', 'SLO'],
      connects: [{ to: 'All internal apps', how: 'Routes identity through this system' }],
      engineerDetail: {
        problem: 'Cross-application cookie architecture required custom domain-level redirect validation. Spring Security\'s built-in CSRF protection directly conflicted with the cross-domain cookie sharing model required for SSO.',
        rejected: [
          { w: 'Spring Security OAuth2', r: 'Default CSRF intercepted cross-app redirect flows — more risk than writing custom.' },
          { w: 'Shared JWT secret', r: 'Every app holds the signing key. Rotation requires coordinated redeploy of all 10+ apps.' },
        ],
        decision: 'Custom SSO with RS256 JWT. Apps hold public key only, never signing key. Key rotation affects only the auth service. SSO_SESSION cookie scoped to root domain; apps validate via /verify endpoint.',
        impl: '<code>JWT</code> RS256: userId, sessionId, deviceHash, appId, roles[]\n<code>SLO:</code> logout fires async callbacks to all registered app logout endpoints\n<code>PassKey:</code> WebAuthn challenge-response, device-bound credentials',
        lesson: 'The SSO system is a trust broker, not an auth library. Asymmetric keys for verify-without-sign.',
      }
    },

    // ── HERO: API Forge ───────────────────────────────────────────────────────
    {
      id: 'api-forge',
      name: 'API Forge',
      subtitle: 'DEVELOPER TOOL',
      district: 'hero',
      pos: [8, -4],
      size: [5, 5],
      height: 14,
      color: 0x003300,
      glowColor: '#7dff4f',
      roofColor: 0x005500,
      windowColor: 0xaaffaa,
      type: 'factory',
      isHero: true,
      icon: '⚙️',
      tag: 'FLOW CHAINING · SWAGGER · COVERAGE',
      status: 'ACTIVE',
      year: '2024',
      metrics: [{ v: 'CHAIN', l: 'FLOWS' }, { v: 'ZERO', l: 'BOTTLENECK' }, { v: 'FULL', l: 'COVERAGE' }],
      story: 'Teams tested APIs manually — copying response values by hand into the next request, running tests one at a time, filing bugs that were impossible to reproduce.\n\n<em>Aditya built an internal testing platform beyond what Postman offers.</em> Swagger auto-discovery. API flow chaining — output of one request feeds the next. Dynamic variable injection. DB console. Coverage tracking.',
      outcome: 'Testing hours cut to minutes. Every endpoint has documented coverage. Bugs are reproducible.',
      tech: ['Java', 'Spring Boot', 'OpenAPI 3.0', 'JSONPath', 'JDBC', 'PDF Export', 'Excel'],
      connects: [{ to: 'All backend services', how: 'Tests every API across Dev/QA/Prod' }],
      engineerDetail: {
        problem: 'Postman has no dependent API chain concept. No coverage tracking. Three separate collections for Dev/QA/Prod that always drift out of sync.',
        rejected: [
          { w: 'Extend Postman', r: "Runner is a black box. No control over execution model, no DB validation, no chaining." },
          { w: 'RestAssured + JUnit', r: 'Requires engineers to write test code. QA team is not Java developers.' },
        ],
        decision: 'Purpose-built tool with Swagger/OpenAPI as source of truth for discovery. Flow chaining uses a DAG: each step declares JSONPath extractors, targeting variable slots in subsequent steps.',
        impl: '<code>Swagger ingestion:</code> parse OpenAPI 3.0, auto-generate stubs\n<code>DAG execution:</code> steps as nodes with extractors → variable slots\n<code>DB Console:</code> JDBC pool per environment, post-step DB assertions',
        lesson: 'When a step fails: fail-fast with full execution log showing which variable failed to resolve. 10× faster debugging.',
      }
    },

    // ── Cloud District ────────────────────────────────────────────────────────
    {
      id: 'cloud-district',
      name: 'Cloud District',
      subtitle: 'AWS MIGRATION HQ',
      district: 'cloud',
      pos: [28, -4],
      size: [6, 4],
      height: 12,
      color: 0x001133,
      glowColor: '#00c8ff',
      roofColor: 0x002255,
      windowColor: 0x66aaff,
      type: 'skyscraper',
      icon: '☁️',
      tag: 'MULE ESB → AWS LAMBDA',
      status: 'OPERATIONAL',
      year: '2023',
      metrics: [{ v: '80+', l: 'MIGRATED' }, { v: '1', l: 'SPOF REMOVED' }, { v: 'ZERO', l: 'DOWNTIME' }],
      story: '80+ business processes ran through a single Mule ESB. One crash = all 80 fail simultaneously.\n\n<em>Aditya led the full migration.</em> Each process now runs independently — Lambda or standalone Java JAR. Designed the script.sh execution layer for scheduling and parameter injection.',
      outcome: 'Each of 80+ processes now fails independently. What was one catastrophic failure domain is now 80 isolated ones.',
      tech: ['AWS Lambda', 'SQS', 'Java', 'Mule ESB', 'Shell Scripting', 'Cron'],
      connects: [{ to: 'Data Vaults', how: 'Ran in parallel — both modernized the platform' }],
      engineerDetail: {
        problem: 'Mule ESB: centralized bus. 80+ flows share one JVM, one thread pool. GC pause in any one flow brings all 80 down.',
        rejected: [
          { w: 'Mule ESB HA cluster', r: 'Doubles license cost. Still shared JVM — rogue flow exhausts thread pools.' },
          { w: 'Single Spring Boot replacement', r: 'Same SPOF problem, different technology.' },
        ],
        decision: 'One deployment unit per integration. Lambda for event-triggered. JAR + cron for batch. script.sh handles all variability without embedding it in Java code.',
        impl: '<code>Lambda:</code> stateless, triggered by SQS/SNS, one responsibility each\n<code>script.sh:</code> sources env config → typed args to JAR → exit code → log → retry\n<code>Migration sequence:</code> Mule analysis → parity test → parallel run → disable → unregister',
        lesson: 'script.sh decouples scheduling from execution logic, makes every job testable independently of its deployment environment.',
      }
    },

    // ── The Bridge ────────────────────────────────────────────────────────────
    {
      id: 'the-bridge',
      name: 'The Bridge',
      subtitle: 'LEGACY INTEGRATION',
      district: 'cloud',
      pos: [26, 8],
      size: [7, 3],
      height: 4,
      color: 0x1a1a00,
      glowColor: '#7dff4f',
      roofColor: 0x333300,
      windowColor: 0xffff88,
      type: 'bridge',
      icon: '🌉',
      tag: 'JAVA 1.7 · IBM MQ · BACKWARD COMPAT',
      status: 'OPERATIONAL',
      year: '2023',
      metrics: [{ v: '0', l: 'REWRITES' }, { v: 'SOLO', l: 'DESIGNED' }, { v: 'LIVE', l: 'RUNNING' }],
      story: 'IBM MQ ran on Java 1.7. The new database needed MySQL 8. MySQL 8\'s JDBC driver requires Java 1.8. IBM MQ upgrade: blocked by license cost. Rewrite: months of risk.\n\n<em>Aditya designed a backward compatibility architecture. Solo. Neither side needed to change.</em>',
      outcome: 'Integration live with zero changes to either legacy system. Still running.',
      tech: ['Java 1.7', 'Java 1.8', 'IBM MQ', 'MySQL 8', 'Runtime.exec', 'Shell Script'],
      connects: [{ to: 'Data Vaults', how: 'Enabled MySQL 8 migration for legacy systems' }],
      engineerDetail: {
        problem: 'IBM MQ client jar compiled for Java 1.7 bytecode. MySQL 8 JDBC requires java.time (Java 1.8). ClassFormatError at runtime. Physical JVM classloader constraint.',
        rejected: [
          { w: 'MySQL 5.x driver', r: 'Breaks on caching_sha2_password (MySQL 8 default auth), strict mode differences.' },
          { w: 'Downgrade to MySQL 5', r: 'MySQL 5→8 migration already in progress platform-wide.' },
        ],
        decision: 'Two JVM processes with different classpath isolation. Java 1.8 bridge process handles MySQL. Java 1.7 invokes it via Runtime.exec with typed key=value arguments. Stateless bridge.',
        impl: '<code>Bridge main():</code> typed args op=UPDATE id=123. Exit codes: 0=success, 1=runtime, 2=config\n<code>Legacy:</code> Runtime.exec("script.sh op=UPDATE id=123"). Reads stdout. Checks exit.',
        lesson: 'Runtime.exec is usually a code smell; here it\'s the correct architectural primitive for classloader isolation.',
      }
    },

    // ── Data Vaults ───────────────────────────────────────────────────────────
    {
      id: 'data-vaults',
      name: 'Data Vaults',
      subtitle: 'MYSQL MIGRATION HQ',
      district: 'foundation',
      pos: [-26, -4],
      size: [6, 6],
      height: 8,
      color: 0x1a1000,
      glowColor: '#ffcc44',
      roofColor: 0x332200,
      windowColor: 0xffdd88,
      type: 'bunker',
      icon: '🏦',
      tag: 'MYSQL 5→8→8.4 · 3 MIGRATIONS',
      status: 'OPERATIONAL',
      year: '2023',
      metrics: [{ v: '3×', l: 'MIGRATIONS' }, { v: '0', l: 'DATA LOST' }, { v: '<10m', l: 'CUTOVER' }],
      story: 'AWS deprecated MySQL 5. The entire platform depended on it. 80+ services, live enterprise clients.\n\n<em>Led three sequential MySQL migrations over two years.</em> 5.x → 8.0 → 8.4. Zero data lost. Clients never knew.',
      outcome: 'Platform on fully supported MySQL. Three cutovers, each under 10 minutes. Zero data lost.',
      tech: ['MySQL 5.x', 'MySQL 8.0', 'MySQL 8.4', 'Connector/J', 'Hibernate', 'Shadow DB'],
      connects: [{ to: 'The Bridge', how: 'Bridge enabled MySQL 8 for legacy systems' }],
      engineerDetail: {
        problem: 'MySQL 8 STRICT mode was off by default in 5.x — years of queries silently truncating strings, inserting zero-dates, using non-deterministic GROUP BY. Migration surfaces all as hard errors. 80+ services.',
        rejected: [
          { w: 'STRICT_TRANS_TABLES=off in MySQL 8', r: 'Migration "succeeds" while keeping all latent bugs.' },
          { w: 'Automated query rewriting', r: 'Tools catch syntactic issues but not semantic ones — truncated string may be business-critical data.' },
        ],
        decision: 'Shadow validation. Run MySQL 5 and 8 in parallel. Replay production writes to MySQL 8 asynchronously. Compare. Fix discrepancies before cutover.',
        impl: '<code>STRICT audit categories:</code> GROUP BY violations → ANY_VALUE(), zero-dates → NULL, string truncation → widened columns\n<code>Auth plugin:</code> mysql_native_password → caching_sha2_password\n<code>Each cutover:</code> snapshot → batch switchover → validation → rollback checkpoint',
        lesson: 'Real work in a DB migration is surfacing assumptions. MySQL 5\'s lax mode was encoding data corruption silently. Shadow period made invisible bugs visible.',
      }
    },

    // ── LedgerFlow ────────────────────────────────────────────────────────────
    {
      id: 'ledgerflow',
      name: 'LedgerFlow',
      subtitle: 'FINANCIAL DISTRICT',
      district: 'foundation',
      pos: [-28, 8],
      size: [4, 4],
      height: 10,
      color: 0x1a0800,
      glowColor: '#ff6b00',
      roofColor: 0x331100,
      windowColor: 0xffaa66,
      type: 'skyscraper',
      icon: '💳',
      tag: 'PO · INVOICING · IDEMPOTENCY',
      status: 'ACTIVE',
      year: '2024',
      metrics: [{ v: 'IDEM', l: 'POTENT' }, { v: 'NO 2PC', l: 'BY DESIGN' }, { v: 'STATE', l: 'MACHINE' }],
      story: 'Financial records cannot be wrong, duplicated, or lost — even when the same message arrives twice.\n\n<em>Designed LedgerFlow with idempotency keys and a strict state machine.</em> DRAFT → PENDING → APPROVED → INVOICED → PAID. Same request twice = same result, always.',
      outcome: 'Duplicate invoice creation is architecturally impossible. Real money, zero errors.',
      tech: ['Java 17', 'Spring Boot', 'MySQL 8', 'State Machine', 'Idempotency Keys'],
      connects: [{ to: 'Auth Tower', how: 'Financial ops are role-protected' }],
      engineerDetail: {
        problem: 'At-least-once message delivery means same message can arrive twice. 2PC was the obvious candidate — evaluate it.',
        rejected: [
          { w: '2-phase commit (2PC)', r: 'Locks across a network round-trip. Coordinator failure = both services stuck. Availability cost too high.' },
          { w: 'Saga with compensating transactions', r: 'Reversing an invoice after it\'s been emailed is not a technical rollback — it\'s a business process.' },
        ],
        decision: 'Clear ownership + idempotency keys + state machine. No distributed transactions if: each entity has one owner, every op accepts an idempotency key, state transitions validated against a matrix.',
        impl: '<code>Idempotency key:</code> client generates UUID → server checks idempotency_log → cached result or execute+store\n<code>State machine:</code> DRAFT→PENDING→APPROVED→INVOICED→PAID. Invalid: HTTP 409 + {currentState, validTransitions[]}\n<code>Same pattern Stripe uses.</code>',
        lesson: 'Distributed transaction and consistency are not synonyms. Design ownership boundaries correctly and make every op naturally idempotent.',
      }
    },

    // ── Monolith Quarter ──────────────────────────────────────────────────────
    {
      id: 'monolith',
      name: 'Monolith Quarter',
      subtitle: 'REDSKY · THE ORIGIN',
      district: 'foundation',
      pos: [-22, 0],
      size: [5, 5],
      height: 7,
      color: 0x0f0800,
      glowColor: '#ff6b00',
      roofColor: 0x1a1000,
      windowColor: 0xffcc88,
      type: 'factory',
      icon: '🏭',
      tag: 'STRUTS2 · SPRING 3 · THE FOUNDATION',
      status: 'OPERATIONAL',
      year: '2022',
      metrics: [{ v: '2022', l: 'JOINED' }, { v: 'WEEKS', l: 'TO PROD FIX' }, { v: 'LIVE', l: 'ENTERPRISE' }],
      story: 'Placed on RedSky — a large B2B relocation platform built on Struts2/Spring3/Hibernate5. So tightly coupled most engineers needed months before touching production safely.\n\n<em>Delivered production fixes within weeks of joining.</em> Built the Relocation Dashboard. Developed deep understanding of the full business lifecycle.',
      outcome: 'Became trusted on live enterprise code in weeks, not months. Every system built afterward carries these lessons.',
      tech: ['Struts 2', 'Spring 3', 'Hibernate 5', 'MySQL 5.x', 'Java 8'],
      connects: [{ to: 'Everything', how: 'Every system built afterward informed by discipline learned here' }],
      engineerDetail: {
        problem: 'Not "it\'s old tech" — it\'s change locality. A change in Customer File has non-obvious effects in Survey, Shipment, Service Order, Work Ticket through shared Hibernate entities and Spring bean chains.',
        rejected: [
          { w: 'Read whole codebase first', r: 'Not practical. Code doesn\'t explain why things are the way they are.' },
          { w: 'Small changes to see what breaks', r: 'Live enterprise clients. Breaking production is not an acceptable learning method.' },
        ],
        decision: 'Trace-first methodology. Before touching any code: trace the complete data path end-to-end. Trace backward too: what else references this entity?',
        impl: '<code>Domain model:</code> Customer Info → Customer File → Survey → Shipment → Service Order → Work Ticket → Account Claiming\n<code>First fix:</code> traced DashboardAction → RelocationService → HQL → found GROUP BY silently wrong in MySQL 5',
        lesson: 'Legacy systems are a change-locality problem. Trace before touching. This skill transferred to every system designed afterward.',
      }
    },

    // ── Architecture Quarter ──────────────────────────────────────────────────
    {
      id: 'arch-quarter',
      name: 'Arch Quarter',
      subtitle: 'ATS · OPS APP',
      district: 'hero',
      pos: [-6, -14],
      size: [5, 4],
      height: 9,
      color: 0x100020,
      glowColor: '#c084fc',
      roofColor: 0x1a0033,
      windowColor: 0xddaaff,
      type: 'modern',
      icon: '🏗️',
      tag: 'GREENFIELD · LEAD ARCHITECT',
      status: 'OPERATIONAL',
      year: '2024',
      metrics: [{ v: '2×', l: 'SYSTEMS' }, { v: 'LEAD', l: 'ARCHITECT' }, { v: 'PROD', l: 'RUNNING' }],
      story: 'High-value art assets moving between cities with zero tracking. Field operations teams with no digital tools.\n\n<em>Led backend architecture for two greenfield systems from zero to production.</em> ATS tracks every asset state-to-state. Operations App handles field work even offline.',
      outcome: 'Both systems in production. Full asset audit trail. Field teams work offline and sync on reconnect.',
      tech: ['Java 17', 'Spring Boot', 'MySQL 8', 'State Machine', 'Offline Sync', 'OpenAPI 3.0'],
      connects: [{ to: 'LedgerFlow', how: 'Field ops generate financial records' }],
      engineerDetail: {
        problem: 'ATS: naive if/else transition logic becomes O(N²). Ops App: last-write-wins reconciliation silently discards legitimate server-side updates.',
        rejected: [
          { w: 'Conditional transition logic', r: 'O(N²) conditionals. Adding a state touches every other state. Untestable.' },
          { w: 'Online-only', r: 'Field operatives cannot pause work when signal drops.' },
        ],
        decision: 'ATS: Transition validity matrix — 2D lookup validTransitions[from][to]=boolean. Ops App: optimistic local state with sequence numbers, server replays and detects conflicts.',
        impl: '<code>Transition matrix:</code> PICKED_UP→[IN_TRANSIT], IN_TRANSIT→[DELIVERED,RETURNED]\nInvalid: HTTP 422 + {currentState, validTransitions[]}\n<code>Offline:</code> append-only operation log → sequence stamps → server reconciliation',
        lesson: 'Transition matrix turns state machine from scattered conditional logic into an explicit, testable data structure.',
      }
    },

    // ── Survey Bridge ─────────────────────────────────────────────────────────
    {
      id: 'survey-bridge',
      name: 'Survey Bridge',
      subtitle: 'DATA PIPELINE',
      district: 'hero',
      pos: [6, -14],
      size: [5, 3],
      height: 5,
      color: 0x001122,
      glowColor: '#4dd4ff',
      roofColor: 0x001f3f,
      windowColor: 0x88ccff,
      type: 'bridge',
      icon: '🔗',
      tag: 'PIPELINE · INTEGRATION · 100% AUTO',
      status: 'OPERATIONAL',
      year: '2023',
      metrics: [{ v: '100%', l: 'AUTOMATED' }, { v: '0', l: 'MANUAL' }, { v: '0', l: 'ERROR' }],
      story: 'Survey data disconnected from the operations system. A team member manually copied data every single day.\n\n<em>Designed the full integration pipeline.</em> Customer File → survey scheduling → mobile execution → automatic Service Order creation. Zero human in the loop.',
      outcome: 'Daily manual data entry eliminated. Data arrives the moment a survey is completed.',
      tech: ['Java', 'Spring Boot', 'MySQL', 'Idempotent APIs', 'Mapping Table', 'Mobile State'],
      connects: [{ to: 'Monolith Quarter', how: 'Survey results feed directly into Service Orders' }],
      engineerDetail: {
        problem: 'Survey items and monolith items use different data models. Mobile surveyors work in homes with unreliable signal — must handle partial completion, connectivity loss, crash restart.',
        rejected: [
          { w: 'Periodic batch sync', r: 'Survey done at 3pm, Service Order at midnight. Operational delays cascade.' },
          { w: 'Survey app writes to monolith DB', r: 'Tight coupling. A monolith schema change breaks the survey app.' },
        ],
        decision: 'Server-side pipeline triggered by survey submission. Survey service owns mapping logic and drives monolith via its public API. Mobile state stored server-side incrementally per section.',
        impl: '<code>Mapping table:</code> survey_item_type → monolith_item_category in DB (configurable without redeploy)\n<code>Idempotent submission:</code> survey_id as key → re-submission returns 200 with existing result',
        lesson: 'Configurable mapping table turned a deployment event into a configuration event. Ops added 4 new item types without engineering.',
      }
    },

    // ── MovePulse ─────────────────────────────────────────────────────────────
    {
      id: 'movepulse',
      name: 'MovePulse',
      subtitle: 'TRACKING STATION',
      district: 'cloud',
      pos: [32, 4],
      size: [4, 4],
      height: 6,
      color: 0x1a0800,
      glowColor: '#ff9950',
      roofColor: 0x2a1000,
      windowColor: 0xffcc88,
      type: 'antenna',
      icon: '📡',
      tag: 'REAL-TIME · B2B · SQL PERF',
      status: 'OPERATIONAL',
      year: '2022',
      metrics: [{ v: 'RT', l: 'REAL-TIME' }, { v: 'OPT', l: 'SQL PERF' }, { v: 'B2B', l: 'CLIENTS' }],
      story: 'Enterprise clients had zero visibility into their relocations. Had to call account managers for every update.\n\n<em>Built the backend query layer for real-time tracking</em> — optimized SQL reads from a shared operational database without degrading write performance.',
      outcome: 'Clients see live status at any time. Account manager call volume for status updates dropped.',
      tech: ['MySQL 5', 'EXPLAIN ANALYZE', 'Index-Only Scans', 'Hibernate', 'Spring Data'],
      connects: [{ to: 'Monolith Quarter', how: 'Reads from core operational database' }],
      engineerDetail: {
        problem: 'Tracking reads share the same MySQL instance as all operational writes. Table scans degrade write performance. No read replica available.',
        rejected: [
          { w: 'Read replica', r: 'Infrastructure change requiring DBA approval. Not in scope.' },
          { w: 'Redis cache', r: 'Cache invalidation in high-write environment complex. Stale status unacceptable for clients.' },
        ],
        decision: 'Write queries that are zero-contention: index-covered reads, minimal columns, bounded pagination. Goal: tracking reads invisible to the write path.',
        impl: '<code>EXPLAIN ANALYZE:</code> target "Using index" (index-only scan). Never "Using filesort".\n<code>READ UNCOMMITTED</code> for status reads — stale by milliseconds acceptable, locks are not.',
        lesson: 'READ UNCOMMITTED is a tool, not a smell. Accepting a dirty read in exchange for zero lock contention is the correct tradeoff for status fields.',
      }
    },

    // ── EDUCATION: University of Allahabad ───────────────────────────────────
    {
      id: 'univ-allahabad',
      name: 'University Tower',
      subtitle: 'M.SC. COMPUTER SCIENCE',
      district: 'education',
      pos: [-6, -32],
      size: [6, 6],
      height: 14,
      color: 0x0a0a20,
      glowColor: '#a78bfa',
      roofColor: 0x15153a,
      windowColor: 0xccbbff,
      type: 'university',
      isEducation: true,
      icon: '🎓',
      tag: 'UNIVERSITY OF ALLAHABAD · 2019–2021',
      status: 'COMPLETED',
      year: '2019–2021',
      metrics: [{ v: 'M.Sc.', l: 'DEGREE' }, { v: 'CS', l: 'MAJOR' }, { v: '2021', l: 'GRADUATED' }],
      story: '<em>Master of Science in Computer Science</em>\nUniversity of Allahabad, Prayagraj, India\n2019 – 2021\n\nDeep study of algorithms, data structures, software engineering, database systems, and distributed computing. Built the academic foundation that made every system decision possible.',
      outcome: 'M.Sc. in Computer Science. The theoretical grounding that informs every architecture decision.',
      tech: ['Algorithms', 'Data Structures', 'DBMS', 'Software Engineering', 'Distributed Systems', 'OOP'],
      connects: [{ to: 'Trilasoft (2022)', how: 'M.Sc. directly led to backend architecture career' }],
      engineerDetail: null,
    },

    // ── EDUCATION: M.P. P.G. College ─────────────────────────────────────────
    {
      id: 'mpg-college',
      name: 'M.P.P.G. College',
      subtitle: 'B.SC. MATH · STATS · CS',
      district: 'education',
      pos: [6, -32],
      size: [6, 5],
      height: 9,
      color: 0x0a1a0a,
      glowColor: '#34d399',
      roofColor: 0x0a2a0a,
      windowColor: 0xaaffcc,
      type: 'university',
      isEducation: true,
      icon: '📚',
      tag: 'M.P. P.G. COLLEGE · GORAKHPUR · 2015–2019',
      status: 'COMPLETED',
      year: '2015–2019',
      metrics: [{ v: 'B.Sc.', l: 'DEGREE' }, { v: 'MATH+CS', l: 'MAJOR' }, { v: '2019', l: 'GRADUATED' }],
      story: '<em>Bachelor of Science — Mathematics, Statistics & Computer Science</em>\nM.P. P.G. College, Gorakhpur, India\n2015 – 2019\n\nFoundational studies in pure mathematics, statistical analysis, and computer science. The combination of mathematical rigor and computing fundamentals shaped the analytical approach to system design.',
      outcome: 'B.Sc. with Mathematics, Statistics & CS. Mathematical thinking that informs every data model and algorithm choice.',
      tech: ['Mathematics', 'Statistics', 'Computer Science', 'Programming Fundamentals', 'Discrete Math'],
      connects: [{ to: 'University of Allahabad', how: 'B.Sc. qualified for M.Sc. Computer Science' }],
      engineerDetail: null,
    },
  ],

  // ── ROAD NETWORK ─────────────────────────────────────────────────────────────
  // Defined as a list of waypoints that form the road system
  // The car follows these waypoints on autopilot or can drive freely
  roads: [
    // Main roundabout (center)
    { type: 'circle', cx: 0, cz: 0, radius: 10, width: 5 },
    // North-South main avenue
    { type: 'straight', x1: 0, z1: -50, x2: 0, z2: 50, width: 5 },
    // East-West main boulevard
    { type: 'straight', x1: -50, z1: 0, x2: 50, z2: 0, width: 5 },
    // Education district road
    { type: 'straight', x1: 0, z1: -20, x2: 0, z2: -45, width: 4 },
    // Cloud district road
    { type: 'straight', x1: 14, z1: 0, x2: 38, z2: 0, width: 4 },
    // Foundation district road
    { type: 'straight', x1: -14, z1: 0, x2: -38, z2: 0, width: 4 },
  ],

  // ── WAYPOINTS for guided tour ──────────────────────────────────────────────
  tourWaypoints: [
    { x: 0, z: 8, label: 'START', pause: 1000 },
    { x: -8, z: -4, label: 'Auth Tower', buildingId: 'auth-tower', pause: 3000 },
    { x: 8, z: -4, label: 'API Forge', buildingId: 'api-forge', pause: 3000 },
    { x: -6, z: -14, label: 'Arch Quarter', buildingId: 'arch-quarter', pause: 2000 },
    { x: 6, z: -14, label: 'Survey Bridge', buildingId: 'survey-bridge', pause: 2000 },
    { x: 0, z: -20, label: 'Education District', pause: 500 },
    { x: -6, z: -32, label: 'University', buildingId: 'univ-allahabad', pause: 3000 },
    { x: 6, z: -32, label: 'College', buildingId: 'mpg-college', pause: 3000 },
    { x: 0, z: -20, label: 'Heading to Cloud', pause: 500 },
    { x: 20, z: 0, label: 'Cloud District', pause: 500 },
    { x: 28, z: -4, label: 'Cloud HQ', buildingId: 'cloud-district', pause: 2000 },
    { x: 26, z: 8, label: 'The Bridge', buildingId: 'the-bridge', pause: 2000 },
    { x: 32, z: 4, label: 'MovePulse', buildingId: 'movepulse', pause: 2000 },
    { x: 0, z: 0, label: 'Foundation Zone', pause: 500 },
    { x: -20, z: 0, label: 'Heading west', pause: 500 },
    { x: -26, z: -4, label: 'Data Vaults', buildingId: 'data-vaults', pause: 2000 },
    { x: -28, z: 8, label: 'LedgerFlow', buildingId: 'ledgerflow', pause: 2000 },
    { x: -22, z: 0, label: 'Monolith', buildingId: 'monolith', pause: 2000 },
    { x: 0, z: 8, label: 'Back to Start', pause: 1000 },
  ],
};
